
`include "../../design/rtl/usbf_defines.v"
`include "../../design/rtl/usbf_crc16.v"
`include "../../design/rtl/usbf_crc5.v"
`include "../../design/rtl/usbf_ep_rf_dummy.v"
`include "../../design/rtl/usbf_ep_rf.v"
`include "../../design/rtl/usbf_idma.v"
`include "../../design/rtl/usbf_mem_arb.v"
`include "../../design/rtl/usbf_pa.v"
`include "../../design/rtl/usbf_pd.v"
`include "../../design/rtl/usbf_pe.v"
`include "../../design/rtl/usbf_pl.v"
`include "../../design/rtl/usbf_rf.v"
`include "../../design/rtl/usbf_utmi_if.v"
`include "../../design/rtl/usbf_utmi_ls.v"
`include "../../design/rtl/usbf_wb.v"
//`include "../../design/rtl/usbf_top.v"
